# Generated by Django 4.0.6 on 2022-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
