# Generated by Django 4.0.6 on 2022-07-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_profile_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
