# Generated by Django 4.0.6 on 2022-07-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_navigationmenu_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
