# Generated by Django 4.0.6 on 2022-07-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_delete_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('support', models.CharField(max_length=200)),
            ],
        ),
    ]
