# Generated by Django 4.0.6 on 2022-07-14 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 9, 20, 24, 74348), verbose_name='Ads Created Date'),
        ),
    ]
