# Generated by Django 4.0.6 on 2022-07-14 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_alter_ads_ads_created_alter_ads_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloginfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150, verbose_name='title')),
                ('blog_icon', models.CharField(max_length=100, verbose_name='icon')),
                ('blog_description', models.TextField(verbose_name='blog description')),
            ],
        ),
        migrations.AlterField(
            model_name='ads',
            name='ads_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 9, 55, 38, 787005), verbose_name='Ads Created Date'),
        ),
    ]
