# Generated by Django 4.0.6 on 2022-07-14 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_alter_ads_ads_created_alter_footermenu_menu_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ads',
            name='ads_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 10, 27, 9, 917714), verbose_name='Ads Created Date'),
        ),
    ]
