# Generated by Django 4.0.6 on 2022-07-14 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_enquiry_alter_ads_ads_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ads_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 10, 30, 48, 10624), verbose_name='Ads Created Date'),
        ),
    ]
