# Generated by Django 4.0.6 on 2022-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
