# Generated by Django 4.0.6 on 2022-07-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerManegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('banner_image', models.ImageField(blank=True, upload_to='banner')),
                ('status', models.BooleanField(default=True)),
                ('navigationid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.navigationmenu', verbose_name='Navigation ID')),
            ],
        ),
    ]
