# Generated by Django 4.0.6 on 2022-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_profilesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Disable')),
                ('email', models.CharField(max_length=100, verbose_name='Subscribe Email')),
            ],
        ),
    ]
