# Generated by Django 4.0.6 on 2022-07-14 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_link', models.CharField(max_length=200, verbose_name='Ads Link')),
                ('ads_created', models.DateTimeField(default=datetime.datetime(2022, 7, 14, 9, 19, 53, 413212), verbose_name='Ads Created Date')),
                ('ads_status', models.BinaryField(default=True, verbose_name='Ads Status')),
                ('ads_title', models.CharField(max_length=200, verbose_name='Ads Title')),
            ],
        ),
    ]
