# Generated by Django 4.0.6 on 2022-07-14 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_ads_ads_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 9, 21, 10, 935982), verbose_name='Ads Created Date'),
        ),
    ]
