# Generated by Django 4.0.6 on 2022-07-14 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_ads_ads_image_alter_ads_ads_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 9, 26, 47, 753578), verbose_name='Ads Created Date'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ads_status',
            field=models.BinaryField(default=True),
        ),
    ]
