# Generated by Django 4.0.6 on 2022-07-14 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_alter_ads_ads_created_alter_ads_ads_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='ads_status',
        ),
        migrations.AddField(
            model_name='ads',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Disable'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ads_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 9, 28, 25, 864004), verbose_name='Ads Created Date'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Disable'),
        ),
    ]
