# Generated by Django 4.0.6 on 2022-07-14 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_remove_ads_ads_status_ads_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 9, 29, 34, 958155), verbose_name='Ads Created Date'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Disable'),
        ),
    ]
